### ISSUE TITLE
Permission may be denied to execute mozlz4tool.py

### ISSUE THREAD

**Issue by majorminors** [brettferdosi/choreo#2]
Debian 10

Permission may be denied to execute mozlz4tool.py at lines 89 and 97, causing the script to fail the sed operation as the required file was not created.

Recommend making mozlz4toop.py executable, e.g.:
`chmod u+x "$DIR/mozlz4tool.py"`

**Comment by majorminors** [comment]
On fixing #1 and #2, your script works on Debian 10.

**Comment by brettferdosi** [comment]
The file in the repository has permissions 755.
